"""Add UUID slug to core models for IDOR protection

Revision ID: 4377b2897752
Revises: 75fb1731d357
Create Date: 2026-05-29 06:57:54.660165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision: str = '4377b2897752'
down_revision: Union[str, Sequence[str], None] = '75fb1731d357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_bills_slug'), ['slug'], unique=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_slug'), ['slug'], unique=True)

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_menu_items_slug'), ['slug'], unique=True)

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_shops_slug'), ['slug'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_slug'), ['slug'], unique=True)

    # ### backfill slugs for existing records ###
    connection = op.get_bind()
    tables = ['bills', 'customers', 'menu_items', 'shops', 'users']
    for table_name in tables:
        # We must backfill row by row because each needs a unique UUID.
        # So we fetch the IDs and update them.
        ids = connection.execute(sa.text(f"SELECT id FROM {table_name}")).fetchall()
        for row in ids:
            connection.execute(sa.text(f"UPDATE {table_name} SET slug = :slug WHERE id = :id"), {"slug": uuid.uuid4().hex, "id": row[0]})

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_items_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
