"""Add fleet billing invoices

Revision ID: 55047fb07e51
Revises: 28ef92701a8d
Create Date: 2026-06-08 09:53:17.254400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55047fb07e51'
down_revision: Union[str, Sequence[str], None] = '28ef92701a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_start_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('next_billing_date')
        batch_op.drop_column('billing_start_date')

    # ### end Alembic commands ###
