"""Add GST fields to Shop and Credit Term fields to Customer

Revision ID: 693ed0bb8ef6
Revises: afcaaa6b6d07
Create Date: 2026-07-12 18:59:49.823833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693ed0bb8ef6'
down_revision: Union[str, Sequence[str], None] = 'afcaaa6b6d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_limit', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('credit_balance', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_term_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_term_value', sa.Integer(), nullable=True))

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_registered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gst_number', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('gst_number')
        batch_op.drop_column('gst_registered')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('payment_term_value')
        batch_op.drop_column('payment_term_type')
        batch_op.drop_column('credit_balance')
        batch_op.drop_column('credit_limit')

    # ### end Alembic commands ###
