"""add reserved_quantity to menu_items

Revision ID: 6d58cd538a85
Revises: b0228866b6d4
Create Date: 2026-07-01 13:27:25.652821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d58cd538a85'
down_revision: Union[str, Sequence[str], None] = 'b0228866b6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_quantity', sa.Float(), nullable=False, server_default="0.0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('reserved_quantity')

    # ### end Alembic commands ###
