"""Add tax_rate to MenuItem and subtotal/tax to Bill

Revision ID: 75fb1731d357
Revises: b7c2e9d40f15
Create Date: 2026-05-28 19:56:04.160218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75fb1731d357'
down_revision: Union[str, Sequence[str], None] = 'b7c2e9d40f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_menu_items_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_items_sku'))
        batch_op.drop_column('tax_rate')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('subtotal_amount')

    # ### end Alembic commands ###
