"""Add country_code to shops and customers

Revision ID: afcaaa6b6d07
Revises: f3a1c9d24e6b
Create Date: 2026-07-06 00:23:01.482595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afcaaa6b6d07'
down_revision: Union[str, Sequence[str], None] = 'f3a1c9d24e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
