"""Add status to Bill and upi_id to Shop

Revision ID: b0228866b6d4
Revises: 55047fb07e51
Create Date: 2026-06-08 11:30:09.517620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0228866b6d4'
down_revision: Union[str, Sequence[str], None] = '55047fb07e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upi_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('upi_id')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
