"""Add receipt and printer settings to Shop

Revision ID: bd8addef606e
Revises: 6d58cd538a85
Create Date: 2026-07-02 22:40:03.641990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8addef606e'
down_revision: Union[str, Sequence[str], None] = '6d58cd538a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_footer', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('printer_paper_width', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('printer_alignment', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('printer_alignment')
        batch_op.drop_column('printer_paper_width')
        batch_op.drop_column('receipt_footer')

    # ### end Alembic commands ###
