"""add credit note table and missing credit fields

Revision ID: c4e0ebf302d8
Revises: 693ed0bb8ef6
Create Date: 2026-07-14 15:14:46.828224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e0ebf302d8'
down_revision: Union[str, Sequence[str], None] = '693ed0bb8ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Idempotency guard: on this project's real dev DB, 'credit_notes' and
    # 'credit_payments' were already created out-of-band (Base.metadata.create_all
    # against the live DB, before this migration existed) rather than through a
    # migration. Skip table/index creation where the table is already present so
    # this migration is safe to run on both a clean DB and the drifted one.
    inspector = sa.inspect(op.get_bind())
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'credit_notes' not in existing_tables:
        op.create_table('credit_notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.String(length=36), nullable=True),
        sa.Column('original_bill_id', sa.Integer(), nullable=False),
        sa.Column('shop_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('items_snapshot', sa.JSON(), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['original_bill_id'], ['bills.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('credit_notes', schema=None) as batch_op:
            batch_op.create_index('ix_credit_notes_bill_created', ['original_bill_id', 'created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_credit_notes_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_credit_notes_slug'), ['slug'], unique=True)

    # HAND-FIX: on the real dev DB, this table was already created out-of-band
    # (CreditPayment was added to models.py earlier in the session with no
    # migration) — guarded the same way as credit_notes above.
    if 'credit_payments' not in existing_tables:
        op.create_table('credit_payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.String(length=36), nullable=True),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('shop_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('method', sa.String(length=16), nullable=False),
        sa.Column('note', sa.String(), nullable=True),
        sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('credit_payments', schema=None) as batch_op:
            batch_op.create_index('ix_credit_payments_customer_created', ['customer_id', 'created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_credit_payments_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_credit_payments_slug'), ['slug'], unique=True)

    bill_cols = {c['name'] for c in inspector.get_columns('bills')}
    with op.batch_alter_table('bills', schema=None) as batch_op:
        # HAND-FIX: server_default added so pre-existing bills (all of which were
        # paid in full at the time, since Credit didn't exist yet) read as "Paid"
        # / fully-paid rather than NULL, which would otherwise render blank on
        # receipts/reports and could confuse payment_status-driven UI branches.
        if 'payment_status' not in bill_cols:
            batch_op.add_column(sa.Column('payment_status', sa.String(), server_default='Paid', nullable=True))
        if 'amount_paid' not in bill_cols:
            batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True))
        if 'due_date' not in bill_cols:
            batch_op.add_column(sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))

    customer_cols = {c['name'] for c in inspector.get_columns('customers')}
    with op.batch_alter_table('customers', schema=None) as batch_op:
        # HAND-FIX: server_default so existing customers evaluate as non-credit
        # (False) rather than NULL/None under boolean-equality filters.
        if 'is_credit_customer' not in customer_cols:
            batch_op.add_column(sa.Column('is_credit_customer', sa.Boolean(), server_default=sa.text('false'), nullable=True))
        if 'company_name' not in customer_cols:
            batch_op.add_column(sa.Column('company_name', sa.String(), nullable=True))
        if 'gst_number' not in customer_cols:
            batch_op.add_column(sa.Column('gst_number', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('gst_number')
        batch_op.drop_column('company_name')
        batch_op.drop_column('is_credit_customer')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('credit_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_payments_slug'))
        batch_op.drop_index(batch_op.f('ix_credit_payments_id'))
        batch_op.drop_index('ix_credit_payments_customer_created')

    op.drop_table('credit_payments')

    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_notes_slug'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_id'))
        batch_op.drop_index('ix_credit_notes_bill_created')

    op.drop_table('credit_notes')
    # ### end Alembic commands ###
