"""Add country_code to Shop and Customer

Revision ID: ce8f7a9b1c2d
Revises: bd8addef606e
Create Date: 2026-07-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8f7a9b1c2d'
down_revision: Union[str, Sequence[str], None] = 'bd8addef606e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.String(3), nullable=True))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.String(3), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    # ### end Alembic commands ###
