# Curated IANA timezone choices for the shop settings form.
# Each entry: (iana_name, display_label, continent) — grouped into <optgroup>s.
TIMEZONE_CHOICES: list[tuple[str, str, str]] = [
    ("UTC", "UTC", "General"),

    ("Asia/Kolkata", "India (IST)", "Asia"),
    ("Asia/Dubai", "Dubai (GST)", "Asia"),
    ("Asia/Karachi", "Pakistan (PKT)", "Asia"),
    ("Asia/Dhaka", "Bangladesh (BST)", "Asia"),
    ("Asia/Kathmandu", "Nepal (NPT)", "Asia"),
    ("Asia/Colombo", "Sri Lanka (IST)", "Asia"),
    ("Asia/Singapore", "Singapore (SGT)", "Asia"),
    ("Asia/Kuala_Lumpur", "Malaysia (MYT)", "Asia"),
    ("Asia/Bangkok", "Thailand (ICT)", "Asia"),
    ("Asia/Jakarta", "Indonesia - Jakarta (WIB)", "Asia"),
    ("Asia/Manila", "Philippines (PST)", "Asia"),
    ("Asia/Hong_Kong", "Hong Kong (HKT)", "Asia"),
    ("Asia/Shanghai", "China (CST)", "Asia"),
    ("Asia/Tokyo", "Japan (JST)", "Asia"),
    ("Asia/Seoul", "South Korea (KST)", "Asia"),
    ("Asia/Riyadh", "Saudi Arabia (AST)", "Asia"),
    ("Asia/Qatar", "Qatar (AST)", "Asia"),
    ("Asia/Tel_Aviv", "Israel (IST)", "Asia"),
    ("Asia/Istanbul", "Turkey (TRT)", "Asia"),

    ("Europe/London", "United Kingdom (GMT/BST)", "Europe"),
    ("Europe/Dublin", "Ireland (GMT/IST)", "Europe"),
    ("Europe/Paris", "France (CET)", "Europe"),
    ("Europe/Berlin", "Germany (CET)", "Europe"),
    ("Europe/Madrid", "Spain (CET)", "Europe"),
    ("Europe/Rome", "Italy (CET)", "Europe"),
    ("Europe/Amsterdam", "Netherlands (CET)", "Europe"),
    ("Europe/Moscow", "Russia - Moscow (MSK)", "Europe"),

    ("Africa/Cairo", "Egypt (EET)", "Africa"),
    ("Africa/Lagos", "Nigeria (WAT)", "Africa"),
    ("Africa/Nairobi", "Kenya (EAT)", "Africa"),
    ("Africa/Johannesburg", "South Africa (SAST)", "Africa"),

    ("America/New_York", "US Eastern (ET)", "Americas"),
    ("America/Chicago", "US Central (CT)", "Americas"),
    ("America/Denver", "US Mountain (MT)", "Americas"),
    ("America/Los_Angeles", "US Pacific (PT)", "Americas"),
    ("America/Toronto", "Canada - Toronto (ET)", "Americas"),
    ("America/Vancouver", "Canada - Vancouver (PT)", "Americas"),
    ("America/Mexico_City", "Mexico City (CST)", "Americas"),
    ("America/Sao_Paulo", "Brazil (BRT)", "Americas"),
    ("America/Argentina/Buenos_Aires", "Argentina (ART)", "Americas"),
    ("America/Jamaica", "Jamaica (EST)", "Americas"),
    ("America/Port_of_Spain", "Trinidad and Tobago (AST)", "Americas"),

    ("Australia/Sydney", "Australia - Sydney (AEST/AEDT)", "Oceania"),
    ("Australia/Perth", "Australia - Perth (AWST)", "Oceania"),
    ("Pacific/Auckland", "New Zealand (NZST/NZDT)", "Oceania"),
]
